Kriston issue#178 newsletter uploads
SpeakingInBits/PC2 pull request #185
Opened 2022-10-14 01:11 UTC by dauthi66

Created an Upload Newsletter view, a NewsletterFile model integrated into the database, and methods for the model. Actual newsletter files are stored in the same place. Uploads are displayed on view in descending order. User can delete and rename newsletters. The actual file is never renamed to allow user naming flexibility, unhindered by OS regulations.

2022-10-14 22:56 UTC, JoeProgrammer88 approved these changes
Great work on the CRUD functionality for the Newsletter!

I had to remove the database migration and make a corrected one. There was only one new one for renaming a column but there was no migration to create the Newsletter table in the database. I also made the strings required in the NewsletterFile class since they had a required annotation already. We can merge this in but we would need another PR to pull the newsletters from the database and display them for users on the `/Resources/FocusNewsletters` page

2022-10-15 00:05 UTC, dauthi66 commented
> 

Ah, I thought I had fixed that! Halfway through I wasn't happy with the names, and wanted to make them more in line with other code in the application. I'll get started on modifying the original display for newsletters asap.

2022-10-18 03:14 UTC, JoeProgrammer88 requested changes

2022-10-18 03:14 UTC, JoeProgrammer88 commented on PC2/Controllers/ResourcesController.cs
> +        public async Task <IActionResult> FocusNewsletters(int id)
If this id parameter is unused, let's remove it

2022-10-18 03:14 UTC, JoeProgrammer88 commented on PC2/Views/Resources/FocusNewsletters.cshtml
> +    List<NewsletterFile> newsletterFiles = (List<NewsletterFile>)ViewData["NewsletterFiles"];
Instead of casting let's use model binding. Pass in the List<NewsletterFile> instead of using ViewData

2022-10-18 03:14 UTC, JoeProgrammer88 commented on PC2/Views/Resources/FocusNewsletters.cshtml
> +@for (int i = newsletterFiles.Count - 1; i >= 0; i--)
If we are going to loop through the newsletters backwards it would be good to add a comment to explain that will cause it to print the most recent newsletter first

2022-10-18 21:56 UTC, dauthi66 commented
All requested issues should be solved. I retested to ensure all enhancements still work as intended.

2022-10-19 05:46 UTC, JoeProgrammer88 approved these changes
Your changes look good!

2022-10-19 05:46 UTC, merged