Calendar Index now identifies when http is in the description to crea…
SpeakingInBits/PC2 pull request #186
Opened 2022-10-21 20:29 UTC by dauthi66

When admin user puts http in the description, it will now identify that as the start of a link and create a live link for them.

2022-10-26 20:53 UTC, JoeProgrammer88 approved these changes
It looks like your links are working. I added a couple comments for suggestions on the code. If you don't want to tackle these, we can add an issue to do some code cleanup later on.

It doesn't seem to cause an issue right now, but if the user enters a period "." or a comma "," at the end of their link, that extra character gets placed in the link url. Chrome and Edge don't seem to have an issue with a trailing period. If you want to revise your algorithm to look for the period or comma, that could prevent some future problems from popping up. We could also add it to a future issue to refactor this page

2022-10-26 20:53 UTC, JoeProgrammer88 commented on PC2/Views/Calendar/Index.cshtml
> +                                            if (eventDescription[i] == 'h' && eventDescription[i + 1] == 't'
Could we use IndexOf("http") instead of listing these 4 characters out for more simplicity

2022-10-26 20:53 UTC, JoeProgrammer88 commented on PC2/Views/Events/Index.cshtml
> +                                            @*loop through EventDescription string to search for links*@
It looks like this looping code is duplicated 4 times. We could possibly use a partial view to move this view logic into a single place and call it 4 times. We could pass in the event description to be processed 
https://learn.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-6.0#access-data-from-partial-views

2022-10-27 21:29 UTC, JoeProgrammer88 requested changes

2022-10-27 21:29 UTC, JoeProgrammer88 commented on PC2/Views/Calendar/Index.cshtml
> +                                            if (eventDescription.IndexOf("http") == i)
Since the IndexOf method will search through an entire string and return the index of the string (or -1 if it is not found), we should be able to remove the loop instead of going through character by character and checking if that index matches

2022-10-31 20:43 UTC, dauthi66 commented on PC2/Views/Calendar/Index.cshtml
> +                                            if (eventDescription.IndexOf("http") == i)
But then it wouldn't support multiple links though right?

2022-11-01 02:47 UTC, JoeProgrammer88 commented on PC2/Views/Calendar/Index.cshtml
> +                                            if (eventDescription.IndexOf("http") == i)
I think the current version only highlights the first link which should be good for now. I can ask the client if they plan to use multiple links on events in the future

2022-11-01 02:48 UTC, JoeProgrammer88 approved these changes
I used your partial view for the 2 other blocks of redundant code. Nice job refactoring that out of the view!

2022-11-01 02:48 UTC, merged