Reversed the order of events to chonological order (oldest first).
SpeakingInBits/PC2 pull request #192
Opened 2022-11-04 21:38 UTC by dauthi66

closes #191

2022-11-08 19:20 UTC, JoeProgrammer88 commented on PC2/Controllers/EventsController.cs
> +            List<CalendarEvent> calendarEvents = await CalendarEventDB.GetAllEvents(_context);
Let's not delete old events in the events controller. Since this will run every time a user checks out the calendar that's a lot of loops to run through. Doing the delete on the calendar controller is fine since only the admin will access that page

2022-11-08 19:24 UTC, JoeProgrammer88 requested changes

2022-11-08 19:24 UTC, JoeProgrammer88 commented on PC2/Controllers/CalendarController.cs
> +            foreach (CalendarEvent calendarEvent in calendarEvents)
Instead of pulling all events and going through a loop, can we just have a method to delete old events and query the database for events in the past only?

2022-11-08 19:24 UTC, JoeProgrammer88 commented on PC2/Controllers/EventsController.cs
> +            foreach (CalendarEvent calendarEvent in calendarEvents)
Let's not delete old events in the events controller. Since this will run every time a user checks out the calendar that's a lot of loops to run through. Doing the delete on the calendar controller is fine since only the admin will access that page

2022-11-08 19:24 UTC, JoeProgrammer88 commented on PC2/Views/Calendar/Index.cshtml
> +                @for (int currentDate = eventDateGroups.Count - 1; currentDate >= 0; currentDate--)
Instead of modifying our loops on the page, we can change the CalendarEventDB.GetAllEvents() methods to retrieve the dates in chronological order. Otherwise we are just pulling the events in reverse chronological order and the undoing that with more processing

2022-11-08 19:24 UTC, JoeProgrammer88 commented on PC2/Views/Calendar/Index.cshtml
> +                @for (int currentDate = eventDateGroups.Count - 1; currentDate >= 0; currentDate--)
Changing the query in our database class will also catch this problem in all places because we need to update the Calendar and Events controllers

2022-11-09 21:34 UTC, dauthi66 commented on PC2/Views/Calendar/Index.cshtml
> +                @for (int currentDate = eventDateGroups.Count - 1; currentDate >= 0; currentDate--)
Ah, great points! However it doesn't quite catch everything, the model was also being retrieved in descending order on the view. All is fixed up now though.

2022-11-09 23:07 UTC, dauthi66 commented on PC2/Views/Calendar/Index.cshtml
> +                @for (int currentDate = eventDateGroups.Count - 1; currentDate >= 0; currentDate--)
I found out that model sort was being used because the initial query wasn't sorting correctly, so it was an awkward fix for that. I fixed the query to work correctly now though, as well as only retrieve present/future events.

2022-11-09 23:09 UTC, dauthi66 commented on PC2/Controllers/CalendarController.cs
> +            foreach (CalendarEvent calendarEvent in calendarEvents)
Yes, that makes much more sense. Now it will stay up to date for the users, and only run the more complicated auto delete when an admin looks at the calendar. I cleaned it up, it looks much better now.

2022-11-10 05:52 UTC, JoeProgrammer88 approved these changes
Nice job refactoring those changes! You did a small code change to fix the ordering and add those queries, looks good!

2022-11-10 05:52 UTC, merged