added documentation for ContactPageModel and all fields
SpeakingInBits/PC2 pull request #249
Opened 2023-07-21 23:02 UTC by crex424

I added documentation for all the fields. Let me know if any are inaccurate, or poorly written.

2023-07-24 16:01 UTC, JoeProgrammer88 requested changes

2023-07-24 16:01 UTC, JoeProgrammer88 commented on PC2/Models/ContactPageModel.cs
> +        /// The message for the contact
Would "The message from the contact" be a little more clear?

2023-07-25 00:37 UTC, crex424 commented on PC2/Models/ContactPageModel.cs
> +    /// Represents a contacts information
We definitely can change the documentation. I will get right on enacting the changes you have proposed.

2023-07-25 00:39 UTC, crex424 commented on PC2/Models/ContactPageModel.cs
> +        /// The message for the contact
I could definitely make that description clearer. Will refactor soon.

2023-07-25 00:42 UTC, crex424 commented on PC2/Models/ContactPageModel.cs
> +    /// Represents a contacts information
Alrighty, I have refactored the documentation cited above. Let me know if you want any further changes.

2023-07-25 01:26 UTC, JoeProgrammer88 approved these changes
I think with the revised documentation we are good to merge these changes

2023-07-25 01:51 UTC, crex424 commented
Alrighty, added some more details to the documentation for the Message field. Let me know if the added details are accurate.

2023-07-25 02:41 UTC, merged