Documented Agency Class and all related fields
SpeakingInBits/PC2 pull request #260
Opened 2023-08-04 21:17 UTC by crex424

Documented Agency class and all related fields.
Documented AgencyDisplayViewModel and all related fields.

Let me know if any documentation does not fit the requirements or is inaccurate.

2023-08-07 19:35 UTC, JoeProgrammer88 requested changes

2023-08-07 19:35 UTC, JoeProgrammer88 commented on PC2/Models/Agency.cs
> -
Can we add the spaces back in between properties. I would like a visual break between each property and the start of documentation for the next property
```csharp
public int PropertyName { get; set; }

/// <summary>
/// ...
`

2023-08-07 23:51 UTC, crex424 commented on PC2/Models/Agency.cs
> -
That is a good idea. I will go ahead and implement that request.

2023-08-08 05:43 UTC, JoeProgrammer88 commented on PC2/Models/Agency.cs
> -
Looks good!

2023-08-08 05:43 UTC, JoeProgrammer88 approved these changes

2023-08-08 05:43 UTC, merged